"""add spire-codex models

Revision ID: 486713675d60
Revises: 
Create Date: 2026-03-08 07:01:38.925657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '486713675d60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('is_x_cost', sa.Boolean(), nullable=True),
    sa.Column('is_x_star_cost', sa.Boolean(), nullable=True),
    sa.Column('star_cost', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('powers_applied', sa.JSON(), nullable=True),
    sa.Column('cards_draw', sa.Integer(), nullable=True),
    sa.Column('energy_gain', sa.Integer(), nullable=True),
    sa.Column('hp_loss', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('vars', sa.JSON(), nullable=True),
    sa.Column('upgrade', sa.JSON(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('beta_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starting_hp', sa.Integer(), nullable=True),
    sa.Column('starting_gold', sa.Integer(), nullable=True),
    sa.Column('max_energy', sa.Integer(), nullable=True),
    sa.Column('orb_slots', sa.Integer(), nullable=True),
    sa.Column('starting_deck', sa.JSON(), nullable=True),
    sa.Column('starting_relics', sa.JSON(), nullable=True),
    sa.Column('unlocks_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enchantments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_card_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_stackable', sa.Boolean(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_weak', sa.Boolean(), nullable=True),
    sa.Column('act', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('monsters', sa.JSON(), nullable=True),
    sa.Column('loss_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('act', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('min_hp_ascension', sa.Integer(), nullable=True),
    sa.Column('max_hp_ascension', sa.Integer(), nullable=True),
    sa.Column('moves', sa.JSON(), nullable=True),
    sa.Column('damage_values', sa.JSON(), nullable=True),
    sa.Column('block_values', sa.JSON(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('potions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flavor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pool', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('character', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rarity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('card_pkey'))
    )
    op.drop_table('relics')
    op.drop_table('potions')
    op.drop_table('monsters')
    op.drop_table('events')
    op.drop_table('encounters')
    op.drop_table('enchantments')
    op.drop_table('characters')
    op.drop_table('cards')
    # ### end Alembic commands ###
