"""add runs

Revision ID: 783c776753a8
Revises: 486713675d60
Create Date: 2026-03-08 08:15:10.234549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '783c776753a8'
down_revision: Union[str, Sequence[str], None] = '486713675d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('build_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('was_abandoned', sa.Boolean(), nullable=False),
    sa.Column('killed_by_encounter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('killed_by_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('character', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ascension', sa.Integer(), nullable=False),
    sa.Column('game_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acts', sa.JSON(), nullable=True),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('platform_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deck_size', sa.Integer(), nullable=False),
    sa.Column('upgraded_card_count', sa.Integer(), nullable=False),
    sa.Column('relic_count', sa.Integer(), nullable=False),
    sa.Column('floor_reached', sa.Integer(), nullable=False),
    sa.Column('bosses_killed', sa.Integer(), nullable=False),
    sa.Column('map_point_counts', sa.JSON(), nullable=True),
    sa.Column('deck', sa.JSON(), nullable=True),
    sa.Column('relics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_build_id'), 'runs', ['build_id'], unique=False)
    op.create_index(op.f('ix_runs_character'), 'runs', ['character'], unique=False)
    op.create_index(op.f('ix_runs_game_mode'), 'runs', ['game_mode'], unique=False)
    op.create_index(op.f('ix_runs_killed_by_encounter'), 'runs', ['killed_by_encounter'], unique=False)
    op.create_index(op.f('ix_runs_seed'), 'runs', ['seed'], unique=False)
    op.create_index(op.f('ix_runs_start_time'), 'runs', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_start_time'), table_name='runs')
    op.drop_index(op.f('ix_runs_seed'), table_name='runs')
    op.drop_index(op.f('ix_runs_killed_by_encounter'), table_name='runs')
    op.drop_index(op.f('ix_runs_game_mode'), table_name='runs')
    op.drop_index(op.f('ix_runs_character'), table_name='runs')
    op.drop_index(op.f('ix_runs_build_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
