"""users

Revision ID: cc235820d68d
Revises: f5158048830d
Create Date: 2026-03-08 12:32:11.070020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc235820d68d'
down_revision: Union[str, Sequence[str], None] = 'f5158048830d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('runs', sa.Column(
        'user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key('runs_user_id_fkey', 'runs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('runs_user_id_fkey', 'runs', type_='foreignkey')
    op.drop_column('runs', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
